apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feature-flag-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/reaperkrew/k8s-learning-repo
    path: .
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: feature-flag-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
